### ISSUE TITLE
Skynote bug

### ISSUE THREAD

**Issue by A-random-githuber** [Rosemoe/RhythmAuto#5]
So I just tested the new apk-debug. When I load a chart to test, it shows the bug. The bot taps the skynote, its input follows the trace after tapping the skynote. Although it doesn't do much errors while autoplaying, I felt kinda annoying lol

Here's a vid of it: [Here](https://youtu.be/nIo4DdmHqD8)
`Sorry for no sounds`

**Comment by A-random-githuber** [comment]
Oh and it also happens with arcs as well

**Comment by Rosemoe** [comment]
I will solve this soon. Actually it is not a bug. It is just caused by my laziness...
The actual position sent to game is correct, so it will not affect autoplaying. The only problem is that there are some logical mistakes in my computing process for the pointer display.

**Comment by A-random-githuber** [comment]
Ah okay lol
Thx for replying!
